{{- if .Values.rbac.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-outpost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-outpost.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.outpost.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end -}}