apiVersion: v2
name: steadybit-platform
description: steadybit Platform Helm chart for Kubernetes.
version: 1.0.20
appVersion: 2.0.17
home: https://www.steadybit.com/
icon: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
maintainers:
  - email: daniel.reuter@steadybit.com
    name: Daniel Reuter
sources:
  - https://github.com/steadybit/helm-charts
annotations:
  artifacthub.io/images: |
    - name: logo
      image: https://steadybit-website-assets.s3.amazonaws.com/logo-symbol-transparent.png
  artifacthub.io/links: |-
    - name: steadybit website
      url: https://www.steadybit.com
    - name: steadybit Kubernetes Helm charts
      url: https://github.com/steadybit/helm-charts
dependencies:
  - name: postgresql
    version: 12.12.10
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
