{{- if .Values.rbac.create -}}
{{- if .Values.rbac.clusterrole }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-agent.clusterRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
rules:
  - apiGroups: [ "" ]
    resources:
      - "services"
      - "pods"
    verbs: [ "get", "list", "watch" ]
{{- else }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-agent.clusterRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
rules:
  - apiGroups: [ "" ]
    resources:
      - "services"
      - "pods"
    verbs: [ "get", "list", "watch" ]
{{- end -}}
{{- end -}}