{{- if .Values.rbac.create -}}
{{- if eq .Values.rbac.roleKind "clusterrole" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "steadybit-agent.clusterRoleName" . }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "steadybit-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "steadybit-agent.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
{{- end -}}