apiVersion: v1
kind: Secret
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.agent.key }}
  key: {{ .Values.agent.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.agent.auth.oauth2.clientSecret.value }}
  oauth2ClientSecret: {{ .Values.agent.auth.oauth2.clientSecret.value | b64enc | quote }}
  {{- end }}
  {{- if .Values.agent.auth.oauth2.tls.clientCertificate.key.password.value }}
  oauth2ClientKeyPassword: {{ .Values.agent.auth.oauth2.tls.clientCertificate.key.password.value | b64enc | quote }}
  {{- end }}
  {{- if .Values.agent.extensions.tls.clientCertificate.key.password.value }}
  extensionsClientKeyPassword: {{ .Values.agent.extensions.tls.clientCertificate.key.password.value | b64enc | quote }}
  {{- end }}
