apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "steadybit-platform.fullname" . }}
  labels:
    {{- include "steadybit-platform.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.platform.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ coalesce .Values.platform.service.type .Values.service.type }}
  ports:
    {{- if .Values.platform.portSplit.enabled }}
    - port: 8081
      name: egress-port
      protocol: TCP
      targetPort: 8081
    - port: 8082
      name: ingress-port
      protocol: TCP
      targetPort: 8082
    {{- else }}
    - port: 80
      name: ui-port
      protocol: TCP
      targetPort: 8080
    - port: 7878
      name: websocket-port
      protocol: TCP
      targetPort: 7878
    {{- end }}
  selector:
    {{- include "steadybit-platform.selectorLabels" . | nindent 4 }}