
name: Bump Chart Version
on:
  workflow_call:
    inputs:
      chart:
        type: string
        required: true
        description: The chart to bump the version for
      app_version:
        type: string
        required: false
        description: The optional app version to set

jobs:
  bump-chart-version:
    name: Bump Chart Patch Version on main branch
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_STEADYBIT_APP_ID }}
          private-key: ${{ secrets.GH_APP_STEADYBIT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      # this commit will effectively cause another run of the workflow which then actually performs the helm chart release
      - run: |
          npm install -g semver
          make chart-bump-version CHART="${{ inputs.chart }}" APP_VERSION="${{ needs.build-images.outputs.version }}"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -am "chore: update helm chart version"
          git push